spring:
  application:
    name: eureka-server

management:
  context-path: /admin

server:
  port: 8761
 
eureka:
  instance:
    hostname: localhost
    registryFetchIntervalSeconds: 1
    leaseRenewalIntervalSeconds: 1
    leaseExpirationDurationInSeconds: 1
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health    
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

  
logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'      